services:
  pallets-api:
    container_name: pallets-api
    working_dir: /app
    build: .
    ports:
      - '${PORT}:3000'
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - db
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}

  db:
    image: postgres:17
    restart: unless-stopped
    tty: true
    ports:
      - '${DB_PORT}:5432'
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - dbdata:/var/lib/postgresql/data

volumes:
  dbdata:
    driver: local
